Feature/eventpage
Swayam-MVJCE/swayam-website-2023 pull request #3
Opened 2023-11-18 18:50 UTC by notBigO

2023-11-21 05:34 UTC, sid-js commented on src/app/page.js
> +const pexel = (id) =>
Can you please abstract this away from the page file. Either put it in component, or a json file and import it.

2023-11-21 05:34 UTC, sid-js commented on src/app/page.js
> +const images = [
Abstract this away to somewhere else

2023-11-21 05:35 UTC, sid-js requested changes
Please do the required small changes

2023-11-22 05:26 UTC, notBigO reviewed
added requested fix and frame focus working now too

2023-11-22 06:03 UTC, notBigO reviewed
refactored code

2023-11-23 04:56 UTC, merged